import { PrismaClient, RegistrationStatus } from '@prisma/client';

const prisma = new PrismaClient();

async function main() {
  console.log('🎓 Seeding Student Registration Records into Neon PostgreSQL...');

  const sampleStudents = [
    {
      regNumber: 'YOSU-2026-00001',
      fullName: 'Asiwaju Sunday Oluwaseun',
      gender: 'MALE',
      dateOfBirth: new Date('2003-04-12'),
      matricNumber: 'FUD/2023/CS/1042',
      jambRegNumber: '202390123456AB',
      faculty: 'Faculty of Computing',
      department: 'Computer Science',
      programme: 'B.Sc. Computer Science',
      level: '300L',
      phone: '+2348031234501',
      whatsapp: '+2348031234501',
      email: 'sunday.asiwaju@student.fud.edu.ng',
      stateOfOrigin: 'Ekiti State',
      lga: 'Ado-Ekiti',
      homeTown: 'Ado-Ekiti',
      residenceType: 'On-Campus',
      hallOfResidence: 'Hall 3 (Ribadu)',
      roomNumber: 'A12',
      residentialAddress: 'Federal University Dutse Campus',
      areaCouncil: 'Main Campus',
      membershipCategory: 'Undergraduate',
      emergencyContactName: 'Mr. Emmanuel Oluwaseun',
      emergencyContactRelationship: 'Father',
      emergencyContactPhone: '+2348021112233',
      status: RegistrationStatus.VERIFIED,
    },
    {
      regNumber: 'YOSU-2026-00002',
      fullName: 'Adeyemi Blessing Folashade',
      gender: 'FEMALE',
      dateOfBirth: new Date('2004-08-25'),
      matricNumber: 'FUD/2024/MIC/2019',
      jambRegNumber: '202490876543CD',
      faculty: 'Faculty of Science',
      department: 'Microbiology',
      programme: 'B.Sc. Microbiology',
      level: '200L',
      phone: '+2348129876502',
      whatsapp: '+2348129876502',
      email: 'folashade.adeyemi@student.fud.edu.ng',
      stateOfOrigin: 'Oyo State',
      lga: 'Ibadan North',
      homeTown: 'Ibadan',
      residenceType: 'Off-Campus',
      residentialAddress: 'Gidan Gada, Dutse',
      areaCouncil: 'Dutse Off-Campus Zone A',
      membershipCategory: 'Undergraduate',
      emergencyContactName: 'Mrs. Titilayo Adeyemi',
      emergencyContactRelationship: 'Mother',
      emergencyContactPhone: '+2348054445566',
      status: RegistrationStatus.VERIFIED,
    },
    {
      regNumber: 'YOSU-2026-00003',
      fullName: 'Olatunji Ibrahim Sobur',
      gender: 'MALE',
      dateOfBirth: new Date('2002-11-19'),
      matricNumber: 'FUD/2022/ACC/0581',
      jambRegNumber: '202290456123EF',
      faculty: 'Faculty of Management Sciences',
      department: 'Accounting',
      programme: 'B.Sc. Accounting',
      level: '400L',
      phone: '+2348145556603',
      whatsapp: '+2348145556603',
      email: 'sobur.olatunji@student.fud.edu.ng',
      stateOfOrigin: 'Osun State',
      lga: 'Ilesa East',
      homeTown: 'Ilesa',
      residenceType: 'On-Campus',
      hallOfResidence: 'Hall 1 (Dan Fodio)',
      roomNumber: 'B08',
      residentialAddress: 'Federal University Dutse Campus',
      areaCouncil: 'Main Campus',
      membershipCategory: 'Undergraduate',
      emergencyContactName: 'Chief Abdulraheem Olatunji',
      emergencyContactRelationship: 'Guardian',
      emergencyContactPhone: '+2348078889900',
      status: RegistrationStatus.VERIFIED,
    },
    {
      regNumber: 'YOSU-2026-00004',
      fullName: 'Akinwale Damilola Grace',
      gender: 'FEMALE',
      dateOfBirth: new Date('2005-01-30'),
      matricNumber: 'FUD/2025/CYB/0104',
      jambRegNumber: '202590778899GH',
      faculty: 'Faculty of Computing',
      department: 'Cyber Security',
      programme: 'B.Sc. Cyber Security',
      level: '100L',
      phone: '+2347061112204',
      whatsapp: '+2347061112204',
      email: 'damilola.akinwale@student.fud.edu.ng',
      stateOfOrigin: 'Ondo State',
      lga: 'Akure South',
      homeTown: 'Akure',
      residenceType: 'Off-Campus',
      residentialAddress: 'Yadi Quarter, Dutse',
      areaCouncil: 'Dutse Central Zone',
      membershipCategory: 'Undergraduate',
      emergencyContactName: 'Pastor Samuel Akinwale',
      emergencyContactRelationship: 'Father',
      emergencyContactPhone: '+2348033334455',
      status: RegistrationStatus.PENDING,
    },
    {
      regNumber: 'YOSU-2026-00005',
      fullName: 'Babalola Solomon Temitope',
      gender: 'MALE',
      dateOfBirth: new Date('2003-09-05'),
      matricNumber: 'FUD/2023/AGE/3092',
      jambRegNumber: '202390665544JK',
      faculty: 'Faculty of Agriculture',
      department: 'Agricultural Economics',
      programme: 'B.Agric. Economics',
      level: '300L',
      phone: '+2349023334405',
      whatsapp: '+2349023334405',
      email: 'temitope.babalola@student.fud.edu.ng',
      stateOfOrigin: 'Kogi State (Okun)',
      lga: 'Kabba/Bunu',
      homeTown: 'Kabba',
      residenceType: 'On-Campus',
      hallOfResidence: 'Hall 4 (Shehu)',
      roomNumber: 'C15',
      residentialAddress: 'Federal University Dutse Campus',
      areaCouncil: 'Main Campus',
      membershipCategory: 'Undergraduate',
      emergencyContactName: 'Dr. Joseph Babalola',
      emergencyContactRelationship: 'Father',
      emergencyContactPhone: '+2348029990011',
      status: RegistrationStatus.VERIFIED,
    },
    {
      regNumber: 'YOSU-2026-00006',
      fullName: 'Ogundele Funke Victoria',
      gender: 'FEMALE',
      dateOfBirth: new Date('2004-03-14'),
      matricNumber: 'FUD/2024/ECO/1183',
      jambRegNumber: '202490332211LM',
      faculty: 'Faculty of Social Sciences',
      department: 'Economics',
      programme: 'B.Sc. Economics',
      level: '200L',
      phone: '+2348087776606',
      whatsapp: '+2348087776606',
      email: 'funke.ogundele@student.fud.edu.ng',
      stateOfOrigin: 'Kwara State',
      lga: 'Ilorin South',
      homeTown: 'Ilorin',
      residenceType: 'Off-Campus',
      residentialAddress: 'Fatara Quarters, Dutse',
      areaCouncil: 'Fatara Zone',
      membershipCategory: 'Undergraduate',
      emergencyContactName: 'Mrs. Bukola Ogundele',
      emergencyContactRelationship: 'Mother',
      emergencyContactPhone: '+2348034441122',
      status: RegistrationStatus.VERIFIED,
    },
  ];

  for (const s of sampleStudents) {
    await prisma.studentRegistration.upsert({
      where: { matricNumber: s.matricNumber },
      update: s,
      create: s,
    });
  }

  console.log('✅ Successfully seeded student registration records!');
}

main()
  .catch((e) => {
    console.error('❌ Error seeding student registrations:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
